#!/usr/bin/env bash
# .claude/hooks/pre-commit-coverage-ratchet.sh
# CLAUDE.md M-4: test coverage must never regress below the committed baseline.
# Reads coverage.xml (generated by pytest --cov-report=xml or jest --coverage).
# Soft-fails if no coverage data found; hard-fails if any module drops below baseline.
#
# Bootstrap: first run creates .coverage-baseline.json from current coverage.
# Refresh baseline intentionally: bash .claude/hooks/pre-commit-coverage-ratchet.sh --refresh-baseline
# then commit .coverage-baseline.json with explanation.

set -uo pipefail
HOOK_NAME="coverage-ratchet"
source "$(dirname "$0")/lib/common.sh"

BASELINE="$REPO_ROOT/.coverage-baseline.json"
DRIFT_BPS="${CODVO_COVERAGE_DRIFT_BPS:-200}"  # 200 bps = 2.00 percentage points tolerance

# ─── refresh-baseline mode ───────────────────────────────────────────────────
if [[ "${1:-}" == "--refresh-baseline" ]]; then
  log_info "refreshing coverage baseline from current coverage data"
fi

# ─── only run when Python source files are staged ────────────────────────────
py_files="$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.py$' \
  | grep -vE '/(tests?|migrations?|alembic/versions|\.venv)/' || true)"

if [[ -z "$py_files" && "${1:-}" != "--refresh-baseline" ]]; then
  log_dim "no Python source files staged — skipping"
  exit 0
fi

# ─── find coverage.xml ───────────────────────────────────────────────────────
COV_XML=""
for candidate in \
  "$REPO_ROOT/coverage.xml" \
  "$REPO_ROOT/backend/coverage.xml" \
  "$REPO_ROOT/coverage/cobertura-coverage.xml"
do
  [[ -f "$candidate" ]] && { COV_XML="$candidate"; break; }
done

if [[ -z "$COV_XML" ]]; then
  log_warn "no coverage.xml found — run tests with --cov-report=xml first"
  log_warn "  Python:     pytest --cov=. --cov-report=xml"
  log_warn "  TypeScript: jest --coverage --coverageReporters=cobertura"
  log_warn "soft-fail: commit allowed until baseline is established"
  exit 1
fi

PY="$(find_python)"
if [[ -z "$PY" ]]; then
  log_warn "no Python interpreter found — skipping coverage ratchet"
  exit 1
fi

"$PY" - "$COV_XML" "$BASELINE" "$DRIFT_BPS" "${1:-}" <<'PY'
import sys, json, pathlib
import xml.etree.ElementTree as ET

cov_xml, baseline_path, drift_bps_str = sys.argv[1], sys.argv[2], sys.argv[3]
refresh_mode = len(sys.argv) > 4 and sys.argv[4] == "--refresh-baseline"
drift_bps = int(drift_bps_str)

tree = ET.parse(cov_xml)
root = tree.getroot()
current = {}
for pkg in root.iter("package"):
    name = pkg.attrib.get("name", "")
    rate = float(pkg.attrib.get("line-rate", "0")) * 100
    current[name] = rate
current["__overall__"] = float(root.attrib.get("line-rate", "0")) * 100

baseline_file = pathlib.Path(baseline_path)

if not baseline_file.exists() or refresh_mode:
    action = "refreshed" if refresh_mode else "bootstrapped"
    print(f"  [{action}] baseline written to {baseline_path}")
    print(f"  overall coverage: {current['__overall__']:.2f}%")
    baseline_file.write_text(json.dumps(current, indent=2, sort_keys=True))
    sys.exit(0)

baseline = json.loads(baseline_file.read_text())

fails = []
ratchet_up = []
for name, base_rate in baseline.items():
    cur = current.get(name)
    if cur is None:
        continue
    if cur + (drift_bps / 100.0) < base_rate:
        fails.append((name, base_rate, cur))
    elif cur > base_rate + 1.0:
        ratchet_up.append((name, base_rate, cur))

if current["__overall__"] + (drift_bps / 100.0) < baseline.get("__overall__", 0):
    fails.append(("__overall__", baseline["__overall__"], current["__overall__"]))

if fails:
    print("  [FAIL] coverage dropped below baseline:")
    for name, base, cur in fails:
        print(f"    {name}: baseline={base:.2f}%  now={cur:.2f}%  delta={cur - base:+.2f}pp")
    print("")
    print("  To fix: add tests for the affected module")
    print("  To update baseline (if coverage drop is intentional):")
    print("    bash .claude/hooks/pre-commit-coverage-ratchet.sh --refresh-baseline")
    print("    git add .coverage-baseline.json && git commit -m 'chore: refresh coverage baseline'")
    sys.exit(2)

if ratchet_up:
    for name, base, cur in ratchet_up[:3]:
        print(f"  [info] {name}: {base:.2f}% → {cur:.2f}% (+{cur-base:.2f}pp) — consider raising baseline")

print(f"  overall: {current['__overall__']:.2f}% (baseline: {baseline.get('__overall__', 0):.2f}%)")
sys.exit(0)
PY

rc=$?
case "$rc" in
  0) ok "coverage ratchet holds" ;;
  2) hard_fail "coverage regression — see above" ;;
  *) log_warn "coverage ratchet exited $rc (soft-fail)"; exit 1 ;;
esac
